//! Top-level application state and main event loop.
//!
//! [`App`] owns the asynchronous [`EventQueue`] and the [`Ui`], and drives
//! the render and event-dispatch cycle.
//!
//! Events generated by the UI are returned to the central event queue as
//! reactions to the currently processed event.

use crate::event::{
    Event, EventEnvelope, EventMetadata, EventQueue, EventSourceLagged, Quit, TerminalEvent,
};
use crate::ui::{Ui, UiEventOutcome};

use crossterm::event::{Event as CrosstermEvent, KeyEvent, MouseEvent};
use ratatui::{DefaultTerminal, Frame};
use tracing::{debug, error, instrument, trace, warn};

/// Maximum permitted reaction depth.
const MAX_EVENT_DEPTH: usize = 64;

/// Top-level application state.
pub struct App {
    /// Whether the main loop should keep running.
    pub running: bool,

    /// Asynchronous event sources and central event queue.
    pub events: EventQueue,

    /// The full UI tree.
    pub ui: Ui,
}

impl Default for App {
    #[instrument(level = "trace")]
    fn default() -> Self {
        let events = EventQueue::default();

        Self {
            running: true,
            events,
            ui: Ui::default_ui().expect("built-in UI must be valid"),
        }
    }
}

impl App {
    /// Creates an application with the default built-in UI.
    #[instrument(level = "trace")]
    pub fn new() -> Self {
        Self::default()
    }

    /// Runs the application's render and event-processing loop.
    #[instrument(skip(self), level = "trace")]
    pub async fn run(mut self, mut terminal: DefaultTerminal) -> color_eyre::Result<()> {
        while self.running {
            let envelope = self.events.next().await?;
            terminal.draw(|frame| self.render(frame, &envelope.metadata))?;

            if envelope.metadata.depth() > MAX_EVENT_DEPTH {
                error!(
                    event = envelope.event_name(),
                    event_id = envelope.metadata.id().get(),
                    parent_id = envelope.metadata.parent_id().map(|id| id.get()),
                    root_id = envelope.metadata.root_id().get(),
                    depth = envelope.metadata.depth(),
                    source = envelope.metadata.source(),
                    max_depth = MAX_EVENT_DEPTH,
                    "dropping event because reaction depth was exceeded"
                );

                continue;
            }

            self.handle_envelope(envelope).await?;
        }

        Ok(())
    }

    /// Handles one event received from [`EventQueue`].
    #[instrument(skip(self), level = "trace")]
    async fn handle_envelope(&mut self, envelope: EventEnvelope) -> color_eyre::Result<()> {
        let envelope = match envelope.try_downcast::<Quit>() {
            Ok(owned) => {
                debug!(
                    event_id = owned.metadata.id().get(),
                    root_id = owned.metadata.root_id().get(),
                    source = owned.metadata.source(),
                    "quit event received"
                );

                self.quit();
                return Ok(());
            }

            Err(envelope) => envelope,
        };

        let envelope = match envelope.try_downcast::<EventSourceLagged>() {
            Ok(owned) => {
                warn!(
                    event_id = owned.metadata.id().get(),
                    root_id = owned.metadata.root_id().get(),
                    source = owned.metadata.source(),
                    "Event lagged"
                );
                return Ok(());
            }
            Err(envelope) => envelope,
        };

        let envelope = match envelope.try_downcast::<TerminalEvent>() {
            Ok(owned) => {
                let metadata = owned.metadata;
                let TerminalEvent(terminal_event) = owned.event;

                self.handle_terminal_event(metadata, terminal_event)?;

                return Ok(());
            }

            Err(envelope) => envelope,
        };

        // Tick and domain events go through the component event path.
        self.dispatch_to_ui(envelope)
    }

    /// Renders the UI.
    #[instrument(skip(self), level = "trace")]
    fn render(&mut self, frame: &mut Frame, metadata: &EventMetadata) {
        self.ui.render(frame, frame.area());
    }

    /// Translates a Crossterm event into UI-generated reactions.
    #[instrument(skip(self), level = "trace")]
    fn handle_terminal_event(
        &mut self,
        metadata: EventMetadata,
        terminal_event: CrosstermEvent,
    ) -> color_eyre::Result<()> {
        let reactions = match terminal_event {
            CrosstermEvent::Key(key_event) => self.handle_key_event(key_event),

            CrosstermEvent::Mouse(mouse_event) => self.handle_mouse_event(mouse_event),

            CrosstermEvent::Resize(width, height) => {
                debug!(
                    width,
                    height,
                    event_id = metadata.id().get(),
                    root_id = metadata.root_id().get(),
                    "terminal resized"
                );

                Vec::new()
            }

            CrosstermEvent::FocusGained => {
                debug!(
                    event_id = metadata.id().get(),
                    root_id = metadata.root_id().get(),
                    "terminal focus gained"
                );

                Vec::new()
            }

            CrosstermEvent::FocusLost => {
                debug!(
                    event_id = metadata.id().get(),
                    root_id = metadata.root_id().get(),
                    "terminal focus lost"
                );

                Vec::new()
            }

            CrosstermEvent::Paste(contents) => {
                debug!(
                    content_length = contents.len(),
                    event_id = metadata.id().get(),
                    root_id = metadata.root_id().get(),
                    "terminal paste event received"
                );

                Vec::new()
            }
        };

        self.enqueue_reactions(&metadata, "app::terminal", reactions.into_iter())
    }

    /// Dispatches a keyboard event into the UI command layer.
    #[instrument(skip(self), level = "trace")]
    pub fn handle_key_event(&mut self, key_event: KeyEvent) -> Vec<Box<dyn Event>> {
        self.ui.handle_key_event(key_event)
    }

    /// Dispatches a mouse event into the UI command layer.
    #[instrument(skip(self), level = "trace")]
    pub fn handle_mouse_event(&mut self, mouse_event: MouseEvent) -> Vec<Box<dyn Event>> {
        self.ui.handle_mouse_event(mouse_event)
    }

    /// Dispatches an application event envelope through the UI components.
    #[instrument(skip(self), level = "trace")]
    fn dispatch_to_ui(&mut self, envelope: EventEnvelope) -> color_eyre::Result<()> {
        let event_name = envelope.event_name();
        let event_id = envelope.metadata.id();
        let root_id = envelope.metadata.root_id();

        trace!(
            event = event_name,
            event_id = event_id.get(),
            parent_id = envelope.metadata.parent_id().map(|id| id.get()),
            root_id = root_id.get(),
            depth = envelope.metadata.depth(),
            source = envelope.metadata.source(),
            "dispatching event to UI"
        );

        match self.ui.dispatch_event(envelope) {
            UiEventOutcome::Ignored(envelope) => {
                trace!(
                    event = envelope.event_name(),
                    event_id = envelope.metadata.id().get(),
                    parent_id = envelope.metadata.parent_id().map(|id| id.get()),
                    root_id = envelope.metadata.root_id().get(),
                    depth = envelope.metadata.depth(),
                    source = envelope.metadata.source(),
                    "event was not handled by application or UI"
                );
            }

            UiEventOutcome::Consumed { cause, reactions } => {
                trace!(
                    event = event_name,
                    event_id = cause.id().get(),
                    root_id = cause.root_id().get(),
                    reaction_count = reactions.len(),
                    "event was consumed by UI"
                );

                self.enqueue_reactions(&cause, "ui::dispatch_event", reactions.into_iter())?;
            }
        }

        Ok(())
    }

    /// Queues generated reactions as children of the given event.
    #[instrument(skip(self, reactions), level = "trace")]
    fn enqueue_reactions(
        &self,
        parent: &EventMetadata,
        source: &'static str,
        reactions: impl Iterator<Item = Box<dyn Event>>,
    ) -> color_eyre::Result<()> {
        for reaction in reactions {
            debug!(
                reaction = reaction.event_name(),
                parent_id = parent.id().get(),
                root_id = parent.root_id().get(),
                next_depth = parent.depth() + 1,
                source,
                "queueing event reaction"
            );

            self.events.send_boxed_reaction(parent, source, reaction)?;
        }

        Ok(())
    }

    /// Stops the main application loop.
    #[instrument(skip(self), level = "trace")]
    pub fn quit(&mut self) {
        self.running = false;
    }
}
